stages:
  ingest:
    cmd: python pipelines/ingest_pipeline.py
    deps:
    - data/raw/creditcard.csv
    - pipelines/ingest_pipeline.py
    - src/components/data_ingestion.py
    outs:
    - artifacts/test.csv
    - artifacts/train.csv
  preprocess:
    cmd: python pipelines/preprocess_pipeline.py
    deps:
    - artifacts/test.csv
    - artifacts/train.csv
    - pipelines/preprocess_pipeline.py
    - src/components/feature_engineering.py
    - src/components/preprocessing.py
    outs:
    - artifacts/test_processed.csv
    - artifacts/train_processed.csv
  train:
    cmd: python pipelines/training_pipeline.py
    deps:
    - artifacts/test_processed.csv
    - artifacts/train_processed.csv
    - pipelines/training_pipeline.py
    - src/components/model_training.py
    params:
    - model.learning_rate
    - model.max_depth
    - model.n_estimators
    outs:
    - models/model.pkl
