services:
  - type: web
    name: fraud-api
    runtime: image
    image:
      url: ghcr.io/nullbitzer0/real-time-fraud-detection/fraud-api:latest
    plan: free
    healthCheckPath: /health
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: fraud-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: fraud-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: fraud-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: fraud-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: fraud-db
          property: database
      - key: REDIS_URL
        sync: false
      - key: LOG_FORMAT
        value: json
      - key: DAGSHUB_REPO_OWNER
        sync: false
      - key: DAGSHUB_REPO_NAME
        sync: false
      - key: DAGSHUB_TOKEN
        sync: false
      - key: MLFLOW_TRACKING_URI
        sync: false

databases:
  - name: fraud-db
    plan: free
    databaseName: fraud
    ipAllowList: []
